name: shared_tools
description: Reusable CLI tools for Flutter projects
version: 0.1.0
environment:
  sdk: ">=3.1.0 <4.0.0"

executables:
  update_dependencies: update_dependencies
  update_android_versions: update_android_versions
  replace_opacity: replace_opacity

dependencies:
  http: ^1.1.0
  yaml: ^3.1.2
